# Generated by Django 2.2.2 on 2019-06-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190626_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
